name: 'Test Server'
description: 'Test Description'
ports:
  game: 1757
  forest: 1761
  rcon: 1758
max-players: 20
pc-world: true
rcon-password: '' # REQUIRED FOR RMEOTE CONSOLE ACCESS, MAKE THIS SECURE!
listing-token: '' # REQUIRED TO BE ON THE SERVER LIST, NEEDS TO BE UNIQUE AND LONG!
